### ISSUE TITLE
Provide Java 8 Compact Profiles images

### ISSUE THREAD

**Issue by kittylyst** [docker-library/java#12]

**Comment by md5** [comment]
Speaking as a non-maintainer, I wouldn't expect to see compact profile variants until they're supported upstream in Debian.

I found some discussion of creating compact variants of the JRE package here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=742864

**Comment by yosifkit** [comment]
Correct. Since that is where we get the current builds of java.  Though there might be other versions coming from other companies later down the road.  Closing for now.

**Comment by yanns** [comment]
Is it something that would be easier now?
It would help having minimal images.
