### ISSUE TITLE
Running app Manifest details are obscured by JRE's Manifest information

### ISSUE THREAD

**Issue by stephen-souness-springer** [docker-library/java#30]
When migrating from a deprecated dockerfile/java image I noticed that the runtime behaviour of my application changed.

The docker image with Oracle Java 8 allowed me to obtain manifest information from my application., e.g. Implementation-Version.

Running the same application with the java:8u40-jre docker image results in the JRE version information showing instead.

**Comment by md5** [comment]
You're going to need to provide more context (or ideally code) for how you were obtaining this information previously.

**Comment by stephen-souness-springer** [comment]
No problem.

I have created a small stand-alone application which should demonstrate the behaviour.

A one line change in the build.gradle file will allow you to switch between base images.

https://github.com/stephen-souness-springer/java-manifest-in-docker

**Comment by md5** [comment]
If you're running `gradlew` outside the container, wouldn't the JAR file created be the same in both cases? I'm curious whether and if how the contents of your `MANIFEST.MF` differ in the two cases.

**Comment by stephen-souness-springer** [comment]
The jar created is the same.

The runtime behaviour is different because the Java runtime is finding a different MANIFEST.MF somewhere in the classpath at runtime.

**Comment by stephen-souness-springer** [comment]
I suspect we will find this is just one of those things that we should expect to encounter.

I'm updating my sample code to show how to get the manifest that we want.

**Comment by md5** [comment]
For what it's worth, I was able to reproduce your problem. This would appear to be a difference between the Oracle and OpenJDK JVM packaging.

Someone else appears to have reported the same issue here: http://stackoverflow.com/questions/14298755/openjdk-only-why-does-getresourceasstream-not-return-manifest-mf-in-executabl
