### ISSUE TITLE
Oracle jdk support

### ISSUE THREAD

**Issue by arnaud-deprez** [docker-library/java#31]
Is there any reason why this official java repository doesn't support the oracle jdk ?
If you are interested, I can prepare a pull request for it.
Keep me in touch.

**Comment by yosifkit** [comment]
I commented on this same issue over in official-images: https://github.com/docker-library/official-images/issues/625#issuecomment-87734364.

**Comment by tianon** [comment]
See also https://github.com/docker-library/docs/pull/203, which is now included in the description on the Hub.
