### ISSUE TITLE
latest should point to Java 8

### ISSUE THREAD

**Issue by benmccann** [docker-library/java#43]
It's surprising to me that tag `latest` for [java](https://registry.hub.docker.com/_/java/) points to Java 7. I'd expect it to be Java 8. Oracle has discontinued support for Java 7 and several prominent Java projects such as Play Framework and Akka have dropped support for Java 7 and this has led people using `java:latest` with those projects to encounter trouble. E.g. see https://groups.google.com/forum/#!topic/play-framework/ImpZ1TX_K6w

**Comment by md5** [comment]
Before https://github.com/docker-library/java/pull/40, the `java:8` image was based on Debian Sid (unstable), so I think it made sense then to leave `latest` pointing at `java:7`. Now that `java:8` is based on `debian:jessie`, however, I think you're right that `latest` can be updated to point to `java:8`.

**Comment by tianon** [comment]
+1 what @md5 said :+1:

**Comment by mkurz** [comment]
:+1:

**Comment by rschanafelt** [comment]
:+1:  I just hit this today using the sbt-native-packager and play 2.4.x

**Comment by md5** [comment]
cf. #44 and https://github.com/docker-library/official-images/pull/850

**Comment by tianon** [comment]
Fixed in #44 :+1:
