### ISSUE TITLE
build from FROM buildpack-deps:jessie-scm instead?

### ISSUE THREAD

**Issue by dhrp** [docker-library/java#45]
I figured out that java is not based on jessie-scm but on jessie-curl (directly) (which doesn't include git). 

I ran into this when using [drone](/drone/drone) for building, as it assumes git in the container. Is there a reason why node and others include scm but java doesn't?

**Comment by dhrp** [comment]
@bradrydzewski, this is probably also interesting for you to know/understand.

**Comment by tianon** [comment]
This is actually JRE vs JDK: https://github.com/docker-library/java/blob/d7d3337acfb3918ef23b3364b2dbf425d5b068cd/openjdk-8-jre/Dockerfile#L1 and https://github.com/docker-library/java/blob/d7d3337acfb3918ef23b3364b2dbf425d5b068cd/openjdk-8-jdk/Dockerfile#L1

If you use the JRE, it's based on `-curl`, but the JDK is based on `-scm`.

**Comment by tianon** [comment]
(which are actually two of the examples in the description itself: https://github.com/docker-library/docs/blob/9a3c64afc13ef2949b626dc7750b98158b14eef0/buildpack-deps/content.md#whats-included)

**Comment by dhrp** [comment]
Thanks @tianon!
