### ISSUE TITLE
bash not working?

### ISSUE THREAD

**Issue by edpichler** [docker-library/java#49]
I'm a Docker novice, should bash work on the java:latest image?

I do 
```
docker run java /bin/bash
```
The Result:
```
Error response from daemon: Cannot start container 732ce634c6bd22abf3cfd19f1e43b6a2d58c8d303f3bab0b2386495179115910: [8] System error: exec: "C:/Program Files/Git/usr/bin/bash": stat C:/Program Files/Git/usr/bin/bash: no such file or directory
```

Should bash work on this images?

**Comment by md5** [comment]
It works for me:

```console
$ docker run --rm java /bin/bash --version
GNU bash, version 4.3.30(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

Did you build the `java` image locally or is that perhaps not the exact command you ran?

**Comment by edpichler** [comment]
@md5 I just pulled with 'docker pull java' command.
I did the same as you now, and it doesn't work.

![captura_de_tela_090415_042027_pm](https://cloud.githubusercontent.com/assets/358696/9692747/a72445f2-5321-11e5-801a-23cb048cae12.jpg)

**Comment by edpichler** [comment]
I will close this issue because it's related with docker core.
https://github.com/docker/docker/issues/16089

**Comment by yosifkit** [comment]
That is a MingGW problem; it sees `/bin/bash` and translates it to `C:/Program Files/Git/usr/bin/bash` before the command is run. Try `docker run java bash`.

**Comment by edpichler** [comment]
If I do this, the #16089 happens.

**Comment by Kberg81** [comment]
I found this little tidbit to get this problem to go away when using docker quick start.

Just add an additional forward slash before bin:

$ docker run --rm java //bin/bash

According to http://tech.lab.carl.pro/tipbase/docker, the issue is caused by Windows trying to resolve the “path” before starting Docker.
