### ISSUE TITLE
what is the relationship between dockerfile/java and docker-library/java?

### ISSUE THREAD

**Issue by chenrui333** [docker-library/java#52]
It looks like dockerfile/java is out of maintenance for a while. And I could not pull from dockerfile/java image.

xx >docker pull dockerfile/java
Using default tag: latest
Pulling repository docker.io/dockerfile/java
Error: image dockerfile/java:latest not found

Thanks,
Rui

**Comment by yosifkit** [comment]
The maintainer of the `dockerfile/*` images was just a community member and they were unable to continue them.  All of those images were turned off to help users transition to supported and up to date images.  This image is maintained by a team sponsored by Docker Inc (https://docs.docker.com/docker-hub/official_repos/).  Many of the Official Repos are maintained by members of the particular project.
