### ISSUE TITLE
JAVA_DEBIAN_VERSION is too old

### ISSUE THREAD

**Issue by jquacinella** [docker-library/java#54]
The JAVA_DEBIAN_VERSION in the file for "java/openjdk-8-jdk/Dockerfile" is currently "8u66-b01-1~bpo8+1". This does not work for me any more, as it results in an error from apt complaining of no package being found. 

Updating this to '8u66-b17-1~bpo8+1' worked for me.

**Comment by tianon** [comment]
Not sure what you mean; the value you listed as working is what's there currently: https://github.com/docker-library/java/blob/master/openjdk-8-jdk/Dockerfile#L16

(as of 200ecf22e5a23cb48cbb3ce47aa08aa3b49a0d2d, ~16 days ago)

**Comment by jquacinella** [comment]
I somehow must have been on an old commit, as I still saw the old version. Looks like this my my mistake!

**Comment by tianon** [comment]
Cool, glad we got it figured out! :+1:
