### ISSUE TITLE
SecureRandom.generateSeed can fail due to lack of entropy

### ISSUE THREAD

**Issue by md5** [docker-library/java#60]
This probably isn't the right place to report this, but I'm starting here in case others run into the same symptom with `java`-based images down the road.

The underlying issue is that Docker containers can sometimes be run on a machine with insufficient `available_entropy`. In the case of `java`-based images, this often manifests as an application hanging while trying to generate a seed value for a PRNG via `SecureRandom.generateSeed(byte[])`.

I've run into this issue a number of times with different images, both with those based on `java` and with others derived from different base images. I've had this occur both on [`boot2docker`](https://github.com/boot2docker/boot2docker) and on EC2. Most recently it came up as a comment on https://github.com/appropriate/docker-jetty/issues/20.

Here's a gist that can reproduce the issue on a low-entropy system, along with the resulting stack trace:

Gist: https://gist.github.com/md5/de5cea7195d757582621

Stacktrace:
```
"main" #1 prio=5 os_prio=0 tid=0x00007fcbb8009800 nid=0x6 runnable [0x00007fcbc0b1b000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:255)
	at sun.security.provider.SeedGenerator$URLSeedGenerator.getSeedBytes(SeedGenerator.java:539)
	at sun.security.provider.SeedGenerator.generateSeed(SeedGenerator.java:144)
	at sun.security.provider.SecureRandom.engineGenerateSeed(SecureRandom.java:139)
	at java.security.SecureRandom.generateSeed(SecureRandom.java:533)
	at SecureRandomTest.main(SecureRandomTest.java:7)
```

There's not much that can be done within the context of this image, but I wanted to raise an issue here for others who run into this problem in the future. Ultimately, the ability to avoid or mitigate this issue will depend on making more entropy available to the JVM and other language runtimes.

I'm fine with this issue being closed as a `WONTFIX` here, but there may be something that can be done in the `boot2docker`/`docker-machine` case to make more of the host system's entropy available to the VM. In the case of other VM hosts with low entropy, the issue may be harder to avoid.

**Comment by md5** [comment]
Here's an upstream discussion for VirtualBox, though this is probably more relevant if I open an issue for `boot2docker` or a related project: https://www.virtualbox.org/ticket/11297

**Comment by tianon** [comment]
Ouch -- I'm not sure there's much we can do here, either at the image level or even at the OS level. :cry:

**Comment by tianon** [comment]
(Except perhaps document that VMs have fairly chronic entropy exhaustion issues in general, perhaps, but I think that'd really be something to document at the Docker level if anything, not necessarily at the image level.)

**Comment by md5** [comment]
> (Except perhaps document that VMs have fairly chronic entropy exhaustion issues in general, perhaps, but I think that'd really be something to document at the Docker level if anything, not necessarily at the image level.)

Like I said before, I mainly wanted to document it here so that others experiencing the same symptoms can find it.

I'll close this issue.

**Comment by tianon** [comment]
:metal: :heart:
